CREATE DATABASE IF NOT EXISTS pericia
    -- DEFAULT CHARACTER SET = '070425';
    
CREATE USER 'perito'@'%' IDENTIFIED BY '250407';
GRANT ALL PRIVILEGES ON pericia.* TO 'perito'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES